{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "52b91bd9-4cf8-4a39-9e94-bd0b34c71f2b",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Importer les bibliothèques nécessaires\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "from imblearn.over_sampling import RandomOverSampler\n",
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "from sklearn.svm import SVC\n",
    "import xgboost as xgb\n",
    "from sklearn.metrics import classification_report, confusion_matrix, mean_squared_error\n",
    "import shap\n",
    "import seaborn as sns\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.model_selection import RandomizedSearchCV\n",
    "\n",
    "# Charger les données\n",
    "df = pd.read_csv('./data/BankFull.csv')\n",
    "\n",
    "# Conversion des variables catégoriques en numériques\n",
    "le = LabelEncoder()\n",
    "for column in df.select_dtypes(include=['object']).columns:\n",
    "    df[column] = le.fit_transform(df[column])\n",
    "\n",
    "# Traitement des données manquantes\n",
    "df.fillna(df.mean(), inplace=True)\n",
    "\n",
    "data_ml = df.drop(columns=['y'])\n",
    "y = df['y']\n",
    "# Diviser les données en ensembles d'entraînement et de test\n",
    "X_train, X_test, y_train, y_test = train_test_split(data_ml, y, test_size=0.2, random_state=42)\n",
    "\n",
    "# Définir le pipeline avec GridSearch ou RandomizedSearch\n",
    "\n",
    "def algorithm_pipeline(X_train, X_test, y_train, y_test, model, param_grid, cv=3):\n",
    "    \"\"\"\n",
    "    Pipeline pour optimiser un modèle avec RandomizedSearch et calculer les prédictions.\n",
    "    \"\"\"\n",
    "    # RandomizedSearch pour hyperparamètres\n",
    "    randomized_search = RandomizedSearchCV(estimator=model,\n",
    "                                           param_distributions=param_grid,\n",
    "                                           scoring='neg_mean_squared_error',\n",
    "                                           n_iter=50, cv=cv, verbose=2, n_jobs=-1, random_state=42)\n",
    "    randomized_search.fit(X_train, y_train)\n",
    "    \n",
    "    # Meilleur modèle\n",
    "    best_model = randomized_search.best_estimator_\n",
    "    \n",
    "    # Prédictions sur l'ensemble de test\n",
    "    y_pred = best_model.predict(X_test)\n",
    "    \n",
    "    # Calculer le score quadratique moyen\n",
    "    mse = mean_squared_error(y_test, y_pred)\n",
    "    print(f\"Mean Squared Error: {mse}\")\n",
    "    \n",
    "    return best_model, y_pred\n",
    "\n",
    "# Hyperparamètres pour XGBoost\n",
    "param_dist = {\n",
    "    'n_estimators': [100, 200, 300],\n",
    "    'learning_rate': [0.01, 0.1, 0.2],\n",
    "    'max_depth': [3, 5, 7],\n",
    "    'min_child_weight': [1, 3, 5],\n",
    "    'subsample': [0.6, 0.8, 1.0],\n",
    "    'colsample_bytree': [0.6, 0.8, 1.0]\n",
    "}\n",
    "\n",
    "# Initialiser le modèle XGBoost\n",
    "xgb_model = xgb.XGBClassifier(random_state=42)\n",
    "\n",
    "# Appliquer le pipeline\n",
    "best_model, y_pred = algorithm_pipeline(X_train, X_test, y_train, y_test, xgb_model, param_dist, cv=5)\n",
    "\n",
    "# Afficher le rapport de classification\n",
    "print(\"Classification Report:\\n\", classification_report(y_test, y_pred))\n",
    "\n",
    "# Crosstab pour résultats\n",
    "display(pd.crosstab(y_test, y_pred, rownames=['Classes réelles'], colnames=['Classes prédites']))\n",
    "\n",
    "# Afficher une heatmap des résultats\n",
    "plt.figure(figsize=(8, 6))\n",
    "sns.heatmap(results, annot=True, fmt='d', cmap='Blues')\n",
    "plt.title('Confusion Matrix')\n",
    "plt.savefig('./outputs/visuals/Confusion_Matrix.png')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e96cdbb4",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Utilisation de SHAP pour l'interprétabilité\n",
    "def plot_shap_summary(model, X_train):\n",
    "    \"\"\"\n",
    "    Génère un graphique SHAP pour l'approche globale des variables.\n",
    "    \"\"\"\n",
    "    # Calculer les valeurs SHAP\n",
    "    explainer = shap.TreeExplainer(model)\n",
    "    shap_values = explainer.shap_values(X_train)\n",
    "\n",
    "    # Générer le graphique récapitulatif\n",
    "    shap.summary_plot(shap_values, X_train, plot_type=\"bar\", show=False)\n",
    "    plt.title('Approche Globale des Variables avec SHAP')\n",
    "    plt.savefig('./outputs/visuals/Approche_Globale_des_Variables_avec_SHAP.png')\n",
    "\n",
    "# Appel de la fonction SHAP\n",
    "plot_shap_summary(best_model, X_train)\n",
    "\n",
    "explainer = shap.Explainer(best_model)\n",
    "shap_values = explainer(X_test)\n",
    "\n",
    "# Summary Plot\n",
    "shap.summary_plot(shap_values, X_test)\n",
    "plt.title('Comparatif Variables')\n",
    "plt.savefig('./outputs/visuals/Comparatifs_Variables.png')\n",
    "\n",
    "# Force Plot pour deux individus\n",
    "shap.initjs()\n",
    "shap.force_plot(explainer.expected_value, shap_values[12,:], X_test.iloc[12,:])\n",
    "shap.force_plot(explainer.expected_value, shap_values[84,:], X_test.iloc[84,:])\n",
    "plt.title('Approche Individuelle')\n",
    "plt.savefig('./outputs/visuals/Approche_Individuelle.png')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
